authentication:
  realms:
    staff:
      modules:
        login:
          type: "login"
          properties:
        otp:
          type: "otp"
          properties:
            driver: "smpp"
        kerberos:
          type: "kerberos"
          properties:
        registration:
          type: "registration"
          properties:
            additionalFileds:
              - dataStore: "cn"
                prompt: "Name"

      authChains:
        login:
          modules:
            - id: "login"
              properties:
        registration:
          modules:
            - id: "registration"
              properties:
        kerberos:
          modules:
            - id: "kerberos"
              properties:

      userDataStore:
        type: "ldap"
        properties:
          address:  "localhost:50389"
          bindDN:   "cn=admin,dc=farawaygalaxy,dc=net"
          password: "passw0rd"
          baseDN:   "ou=users,dc=farawaygalaxy,dc=net"
          objectClasses:
            - "inetOrgPerson"
          userAttributes:
            - "cn"
            - "sn"

session:
  type: "stateless" #could be also stateful, implement later
  expires: 60000
  jwt:
    issuer: 'http://auth-service'
    privateKeyPem: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIBOQIBAAJATmLeD2qa5ejVKJ3rwcSJaZAeRw4CVrUHvi1uVvBah6+6qCdjvH8N
      RT+GOI3ymdnilILPHcn51A0XQAXyrvFkgwIDAQABAkAPZUvIK2ARGBIF0D6l6Dw1
      B6Fqw02iShwjNjkdykd9rsZ+UwsYHJ9xXSa2xp7eGurIUqyaDxF+53xpE9AH72PB
      AiEAlEOIScKvyIqp3ZAxjYUd3feke2AGq4ckoq/dXFvxKHcCIQCHWH+6xKyXqaDL
      bG5rq18VQR2Nj7VknY4Eir6Z6LrzVQIgSz3WbXBi2wgb2ngx3ZsfpCToEUCTQftM
      iU9srFFwmlMCIFPUbMixqHUHi6BzuLDXpDz15+gWarO3Io+NoCCUFbdBAiEAinVf
      Lnb+YDP3L5ZzSNF92P9yBQaopFCifjrUqSS85uw=
      -----END RSA PRIVATE KEY-----


server:
  cors:
    allowedOrigins:
      - http://localhost:3000


